import type { IntakeQuestion } from "@/types/domain";

export const intakeQuestionPool: IntakeQuestion[] = [
  {
    id: "life_rating",
    type: "rating",
    question: "How is life feeling lately?",
    category: "emotional_signal",
    stage: "broad_signal",
    options: [
      { label: "Great", value: "great" },
      { label: "Okay", value: "okay" },
      { label: "Messy", value: "messy" },
      { label: "Overwhelming", value: "overwhelming" },
    ],
  },
  {
    id: "main_worry_area",
    type: "chips",
    question: "Which area feels most confusing right now?",
    category: "life_area",
    stage: "life_area",
    options: [
      { label: "Career", value: "career" },
      { label: "Relationships", value: "relationships" },
      { label: "Purpose", value: "purpose" },
      { label: "Money", value: "money" },
      { label: "Family", value: "family" },
      { label: "Health", value: "health" },
      { label: "Something else", value: "other" },
    ],
  },
  {
    id: "career_situation",
    type: "short_text",
    question: "What's happening in career or work that feels off?",
    category: "career",
    stage: "situation",
    placeholder: "A short sentence is enough",
  },
  {
    id: "relationships_situation",
    type: "short_text",
    question: "What keeps feeling complicated in relationships lately?",
    category: "relationships",
    stage: "situation",
    placeholder: "You can keep it short",
  },
  {
    id: "purpose_situation",
    type: "short_text",
    question: "What feels unclear about purpose or direction right now?",
    category: "purpose",
    stage: "situation",
    placeholder: "Say it in your own words",
  },
  {
    id: "money_situation",
    type: "short_text",
    question: "What feels tense around money right now?",
    category: "money",
    stage: "situation",
    placeholder: "A quick answer works",
  },
  {
    id: "family_situation",
    type: "short_text",
    question: "What feels heavy or tangled in family life lately?",
    category: "family",
    stage: "situation",
    placeholder: "No need to over-explain",
  },
  {
    id: "health_situation",
    type: "short_text",
    question: "What feels off in your body, energy, or mental state?",
    category: "health",
    stage: "situation",
    placeholder: "Short and honest is good",
  },
  {
    id: "other_situation",
    type: "short_text",
    question: "What feels like the real issue underneath all this?",
    category: "other",
    stage: "situation",
    placeholder: "Say it how you'd text it",
  },
  {
    id: "career_pattern",
    type: "chips",
    question: "Which of these sounds most like the career vibe?",
    category: "career",
    stage: "deeper_context",
    options: [
      { label: "Stuck", value: "stuck" },
      { label: "Burned out", value: "burned_out" },
      { label: "Need direction", value: "need_direction" },
      { label: "Want change", value: "want_change" },
      { label: "Comparing myself", value: "comparison" },
    ],
  },
  {
    id: "relationships_pattern",
    type: "chips",
    question: "Which relationship pattern hits closest?",
    category: "relationships",
    stage: "deeper_context",
    options: [
      { label: "Mixed signals", value: "mixed_signals" },
      { label: "Too intense", value: "intense" },
      { label: "Hard to trust", value: "trust" },
      { label: "I overgive", value: "overgiving" },
      { label: "Fear of losing people", value: "fear_of_loss" },
    ],
  },
  {
    id: "purpose_pattern",
    type: "chips",
    question: "What kind of purpose confusion is this?",
    category: "purpose",
    stage: "deeper_context",
    options: [
      { label: "Directionless", value: "directionless" },
      { label: "Outgrew old goals", value: "outgrew_goals" },
      { label: "Split between paths", value: "split_paths" },
      { label: "Need meaning", value: "need_meaning" },
      { label: "Low motivation", value: "low_motivation" },
    ],
  },
  {
    id: "money_pattern",
    type: "chips",
    question: "Which money tension feels truest?",
    category: "money",
    stage: "deeper_context",
    options: [
      { label: "Not enough", value: "not_enough" },
      { label: "Future anxiety", value: "future_anxiety" },
      { label: "Family pressure", value: "family_pressure" },
      { label: "Planning feels messy", value: "planning_messy" },
      { label: "Spending guilt", value: "spending_guilt" },
    ],
  },
  {
    id: "family_pattern",
    type: "chips",
    question: "Which family dynamic feels closest?",
    category: "family",
    stage: "deeper_context",
    options: [
      { label: "Expectations", value: "expectations" },
      { label: "Conflict", value: "conflict" },
      { label: "Distance", value: "distance" },
      { label: "Caretaking pressure", value: "caretaking" },
      { label: "Feeling misunderstood", value: "misunderstood" },
    ],
  },
  {
    id: "health_pattern",
    type: "chips",
    question: "Which health or energy pattern feels closest?",
    category: "health",
    stage: "deeper_context",
    options: [
      { label: "Low energy", value: "low_energy" },
      { label: "Bad sleep", value: "sleep" },
      { label: "Stress spirals", value: "stress_spirals" },
      { label: "Anxious body", value: "anxious_body" },
      { label: "Need balance", value: "need_balance" },
    ],
  },
  {
    id: "other_pattern",
    type: "short_text",
    question: "If you had to name the repeating pattern in one line, what is it?",
    category: "other",
    stage: "deeper_context",
    placeholder: "Keep it simple",
  },
  {
    id: "support_style",
    type: "multiple_choice",
    question: "What would help most right now?",
    category: "support_style",
    stage: "deeper_context",
    options: [
      { label: "Clarity", value: "clarity" },
      { label: "Calm", value: "calm" },
      { label: "Direction", value: "direction" },
      { label: "Validation", value: "validation" },
    ],
  },
  {
    id: "deeper_reflection",
    type: "short_text",
    question: "What do you most want Rah to understand about you right now?",
    category: "reflection",
    stage: "deeper_context",
    placeholder: "One honest sentence is enough",
  },
];

export function getIntakeQuestionById(id: string) {
  return intakeQuestionPool.find((question) => question.id === id) ?? null;
}
